"""
EXISTE DIVERSAS FORMAS DE DOCUMENTAR O SEU CÓDIGO. DENTRE ELAS, PODE-SE SE ENCONTRAR DOCSTRINGS PARA FUNÇÕES, MÉTODOS,
CLASSES, ETC. CASO TENHA ALGUMA DÚVIDA, CONSULTAR O MATERIAL NO SITE.

VERIFICAR TYPEHINTS
"""