a = input('Digite algo: ')
tipo = type(a)
espaços = a.isspace()
número = a.isnumeric()
alfabético = a.isalpha()
alfanumérico = a.isalnum()
maiúscula  = a.isupper()
minúscula = a.islower()
capitalizada = a.istitle()

print(f'O tipo primitivo desse valor é {tipo}')
print(f'Só tem espaços? {espaços}')
print(f'É número? {número}')
print(f'É alfabético? {alfabético}')
print(f'É alfanumérico? {alfanumérico}')
print(f'Está em maiúscula? {maiúscula}')
print(f'Está em minúscula? {minúscula}')
print(f'Está capitalizada? {capitalizada}')
